### ISSUE TITLE
Titanic data set not easily available in the colab 

### ISSUE THREAD

**Issue by icozma** [vizzuhq/ipyvizzu#151]
Now I also see the colab is asking for a password.

**Comment by veghdev** [comment]
@ShruAgarwal If I rerun the colab example, I get the following error:
FileNotFoundError: [Errno 2] No such file or directory: '/content/titanic.csv'

Could you please check what is the problem with the permissions?

**Comment by veghdev** [comment]
@icozma I updated the example. You can see the data with its github [link](https://github.com/vizzuhq/ipyvizzu/raw/main/docs/examples/stories/titanic/titanic.csv)

**Comment by ShruAgarwal** [comment]
@icozma , I'm really sorry that you faced the issue because of my silly mistake. 😐 I won't repeat such code errors next time. 
@veghdev , I'm extremely Sorry that I didn't replied back to solve the issue. Actually, I was facing problems with my Gmail notifications due to which I missed out on many important mails from Github. Just now, I got it fixed. From now onwards, I'll monitor my Github notifications everyday! 🙂

**Comment by icozma** [comment]
No worries, no emergency, I just saw it and thought to raise it. Have a good day! :-)

**Comment by icozma** [comment]
I tested it and it works fine, thank you!
