### ISSUE TITLE
Animation is not showing up in Visual Studio Code

### ISSUE THREAD

**Issue by davidutassy-seon** [vizzuhq/ipyvizzu#190]
I am using VS Code to experiment in Jupyter notebooks, but the animation (titanic example) is not showing up for me there.

**Comment by veghdev** [comment]
Hi @davidutassy-seon,

Could you please try the pure chart (_repr_html_) with `display="manual" `instead of the chart.show()?
See the full code in our compatibility [example](https://github.com/vizzuhq/ipyvizzu/blob/main/docs/examples/environments/vscode.md)

If it still doesn't work, could you please provide more information - what operating system and version of vscode you are using? Thanks.

**Comment by davidutassy-seon** [comment]
Thanks a lot @veghdev! Works! Sorry for not looking it up in the docs.

**Comment by veghdev** [comment]
@davidutassy-seon I'm glad I could help you.
