### ISSUE TITLE
development: customize MkDocs material theme

### ISSUE THREAD

**Issue by simzer** [vizzuhq/ipyvizzu#206]
Change the mkdocs theme to resemble the vizzu lib doc site https://lib.vizzuhq.com/0.4/
- [x] colors, font-sizes
- [x] add vizzu logo, favicon
- [x] syntax highlight
- [x] add social logos/links

**Comment by veghdev** [comment]
github image background in the menu is still blue (mobile view)

**Comment by simzer** [comment]
Syntax highlighting is poor

**Comment by veghdev** [comment]
> Syntax highlighting is poor

I changed pygments to highlightjs because it provides more freedom.
We cannot use both, because I did not find a way to select languages in mkdocs highlight plugin api.

python code snippet highlights are the same with highlightjs, but javascript snippets are better.

still need to set some colors in the css to fully highlight the code reference.
