### ISSUE TITLE
change doc online version

### ISSUE THREAD

**Issue by veghdev** [vizzuhq/ipyvizzu#32]
I have a question about the online version of the documentation.

If I change something in a ipynb file in doc/examples, after that I need to run make doc and commit changed htmls if I want to update the site too? (In that case I do not understand clearly what pages-build-deployment workflow do.)

**Comment by nyirog** [comment]
Github support Jekyll for page building, but we use only a static html, which is a noop from Jekyll point view. That's why we update the htmls manually which is an ugly hack.

We could setup a Jekill config which somehow call `make docs`, but I don't much about Jekill.

An alternate solution would be to use [Sphinx](https://pypi.org/project/Sphinx/) and include the ipynb notebooks into the Sphinx documentation. The [Shinx guide](https://docs.readthedocs.io/en/stable/guides/jupyter.html) says that the npsphinx extension supports this solution. If we have a Sphinx documentation then we can publish it on readthedocs.org, so we don't have to manually generate and source control the html files.

The current solution is just  a temporal solution. The smallest change would be to use Jekyll for doc site generation. But I'm more familiar with Sphinx so I would go in that way.

**Comment by veghdev** [comment]
Thanks. For now, I'm updating the html manually, but I'll read about Sphinx later.

**Comment by simzer** [comment]
What about setting up the doc build in google cloud and trigger it for every commit?

**Comment by veghdev** [comment]
I think it could be done with github action as well.

**Comment by nyirog** [comment]
Most of the python project use Sphinx  + readthedocs.org. But github puts a lot of effort to extend the features of project hosting so the github page with Jekyll could be beneficial, too.

I don't know anything about google cloud but that could be good, too.

**Comment by nyirog** [comment]
> I think it could be done with github action as well.

The github page build is a github action as well, which cannot be edited (as far as I know). I don't know that the page-build is part of the github action api. If we can add page-build step, than it is easy to create a custom pag-build which runs `make docs` as first step.

**Comment by nyirog** [comment]
For a github action the jekyll step may could be skipped. We only need `make docs` + `actions/upload-artifact@main`.

I would like to see the yaml config of `pages-build-deployment`. Does anyone know where it can be found?

**Comment by nyirog** [comment]
Unfortunately the `actions/deploy-pages@v1` uses some token may not be available for custom user action.

**Comment by veghdev** [comment]
It is able to create a token in github secrets and use it in custom actions - if I remember well I will do it.

**Comment by nyirog** [comment]
Please check my draft solution with sphinx https://github.com/vizzuhq/ipyvizzu/pull/34

**Comment by nyirog** [comment]
An other solution would be to use a dedicated branch for github pages. A github action could build the documentation and push it to 'gh-page' branch and the github pages would be built from 'gh-page' branch. The 'main' branch would not contain any html file. The html files would be pushed only to 'gh-page' branch.

**Comment by nyirog** [comment]
The `gh-pages` branch is a smaller change than the transition to `sphinx`, but is we want to add API documentation for `ipyvizzu` then we should use `sphinx` in the future.

Unfortunately I don't know whether `readthedocs.org` support `MyST-NB` sphinx extension.

**Comment by nyirog** [comment]
There is no need for manual update of docs/*.html:
* The `Push doumentation to gh-pages` action builds the html documentation and push the result to the `gh-pages` branch.
* The github page is built from the `gh-pages` branch.

I think we can close this issue.

**Comment by veghdev** [comment]
Many thanks, I haven’t had time to work on this issue.
